### ISSUE TITLE
BUG: Not working LC MOD

### ISSUE THREAD

**Issue by minie0** [Lightman314/LightmansCurrencyFabric#2]
### Minecraft Version

1.19.2

### Fabric Version

0.14.11

### Lightman's Currency Version

1.19.2.1.0.0.1

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Other relevant Mods

![mods1](https://user-images.githubusercontent.com/120258326/206877276-06fedafc-1234-41ae-aa01-20b2ad7a019c.png)
![mods2](https://user-images.githubusercontent.com/120258326/206877278-32cdbf61-4a2c-44ad-89d8-715dfdbdcb22.png)

### Describe the bug

Sorry, I rewrite this report.

I created fabric server. Not single play.

Attach the entire 'latest.log'.
My server is operate normally, But not works LC MOD.

I am extremely grateful for your help.

### To Reproduce

Try to server started.
Server operate normally.
But not reading LC MOD

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/10201040/latest.log)

First time, Didn't works server, and error message ;Invalid player data;
Second time(this time), To connected the server but not working LC mod.

**Comment by Lightman314** [comment]
`[03:58:03] [Server thread/ERROR]: [worlds_together] Error for jar:file:///C:/Users/MINIE/OneDrive/문서/MINNIE/mods/lightmanscurrency-1.18.2-2.0.0.3.jar: java.nio.file.NoSuchFileException: /fabric.mod.json`
^ Copied from line 554 of the latest.log file provided

It isn't working because you are attempting to use `lightmanscurrency-1.18.2-2.0.0.3.jar` (which is a forge version), not the `lightmanscurrency_fabric-1.19.2-1.0.0.1.jar` version that you are claiming in the issue report.

Please try again while actually using the fabric version of the mod, as I have 100% tested that it works as intended on a server (or at least it works as well as it does in single-player, not all features have been fully ported over to fabric yet).

Edit: Also, please do not **ever** include any information not relevant to the issue at hand in your issue report. If you need to add more info to a different issue (or if you believe that it was reported as fixed when it isn't), then just post a comment and/or re-open the first issue instead of adding now-irrelevant info to another issue, making it difficult for me to understand what actually needs to be fixed. If you believe the 2nd issue is related, you can also link to the other issue in the description/comments (i.e. may be related to #1) .

**Comment by minie0** [comment]
Because I was in hurry, I missed it.(LC mod 1.18.2~)

At first, I used LC mod. (ver.1.19.2.1.0.0.1) 
As a result Error message.

I'll continuously retry it. I really appreciate your kind answer.

Thank you!
