### ISSUE TITLE
BUG: Cannot transfer account/leave group

### ISSUE THREAD

**Issue by duskydoesstuff** [Lightman314/LightmansCurrencyFabric#20]
### Minecraft Version

1.19.2

### Fabric Version

0.14.22

### Lightman's Currency Version

1.0.1.0

### Environment Type

Dedicated Server (Bug/crash happened while connected to a server or while the dedicated server was booting)

### Describe the bug

Created a bank account for my friend and added her as admin, attempted to transfer ownership but it still says i am the owner. She can access the bank account. I also cannot leave the account, the only current way to do this is to type my username in the users manager and click remove, but it does nothing.

### To Reproduce

1. create bank account
2. add other player
3. make them admin
4. go to "transfer ownership" and type their user
5. press transfer
6. nothing happens

### Screenshots/Logs/Crash Reports

Notes: I use a player nickname editor, so for example "#name" is a replacement for a username. Also, this log doesn't contain data from when this bug happened, it is the latest as of today. I can upload the other one.
https://pastebin.com/5FpX2y0T

**Comment by Lightman314** [comment]
Please explain in further detail, as you cannot simply "create" a bank account.
Are you creating a **team** and then giving it a bank account? If so, the only way to remove yourself from a team that you are the owner of is to transfer the team's ownership to another player (presumably your friend in this case) through the ownership tab, not the basic team members tab.

Edit: Never mind. Got around to testing, and can confirm that you cannot transfer team ownership for some odd reason... I'll make sure this gets fixed in the next update.

Edit 2: Found the issue (made the packet, but forgot to actually send it for some odd reason, lol). Will be fixed in the next update!

**Comment by Lightman314** [comment]
Fixed in LC Fabric v1.0.1.1
