### ISSUE TITLE
BUG: Coin Trade doesn't work in 1.20.1 fabric

### ISSUE THREAD

**Issue by PlayerQuit** [Lightman314/LightmansCurrencyFabric#33]
### Minecraft Version

1.20.1

### Fabric Version

0.15.11

### Lightman's Currency Version

fabric-1.20.1-1.0.2.3a

### Environment Type

Minecraft Client (Bug/crash happened in a single-player world or while the game was booting)

### Describe the bug

the coin trade doesn't work i don't know why, the common config file of the lightman's currency is set on true for the coin trade of the villagers... rebooted minecraft and/or the config in the game, but nothing even creating a new world

### To Reproduce

open the game with the mod installed without any other mod

### Screenshots/Logs/Crash Reports

[latest.log](https://github.com/Lightman314/LightmansCurrencyFabric/files/15475876/latest.log)

**Comment by Lightman314** [comment]
Replacing emeralds with coins has never worked in LC Fabric due to how it's trade framework is set up, and unfortunately there's not really a whole lot I can do about that :(

Unfortunately my only option at this point is to give up and remove the feature from the fabric version entirely (including the relevant config options so that people don't get confused).

**Comment by holmityd** [comment]
https://github.com/holmityd/ChangeEmeraldTrades/blob/dda2faa2ae078e422c21e31aa131f0f1800dd860/src/main/java/net/architects/CustomVillagerMaterialsMod/mixin/CustomTradeMaterial.java#L95

I think you were looking for that.
